
# Approver & PIN
APPROVER_EMAIL = "sameer.sheikh@omegafinancial.co.in"   # where OTP will be received
APPROVER_PIN   = "4321"

# Gmail SMTP (sender mailbox = same Gmail)
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "465"
SMTP_USER = "sameer.sheikh@omegafinancial.co.in"
SMTP_PASS = "tcsajiutsysxgrpj"          # <-- your code with NO spaces
SMTP_FROM = "sameer.sheikh@omegafinancial.co.in"
SMTP_FROM_NAME = "Omega Financial"
